### ISSUE TITLE
BACK 코드 수정

### ISSUE THREAD

**Issue by ssoyeong-lee** [ShinBeomsoo/capstone_design_3#11]
# Todo
- [ ] ~~불필요한 print문 삭제, 로그 도입~~
- [x] 디버깅 위한 설정 파일 추가
- [x] requirements.txt 파일 수정
